# Generated by Django 2.1 on 2019-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_auto_20190422_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='write_id',
            field=models.IntegerField(default=1, verbose_name='是否为发送者'),
            preserve_default=False,
        ),
    ]
